### PR TITLE
Removed preview reference and updated API version to non-preview

### PR DESCRIPTION
**Pull request by johnlokerse**
## Description

Updated API version to non-preview

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by johnlokerse** [comment]
@jaredfholgate My first Terraform AVM commit ;-) 

I updated the docs to remove the preview warning, but it comes back during `./avm pre-commit` or `./avm pr-check`. What to do? 😄

**Comment by jaredfholgate** [comment]
Thanks @johnlokerse. You need to update the `_header.md` instead of the `README.md` directly.

**Comment by johnlokerse** [comment]
> Thanks @johnlokerse. You need to update the `_header.md` instead of the `README.md` directly.

Done!

**Review by jaredfholgate — APPROVED** [review]
LGTM, moving to a release branch for e2e testing

**Comment by jaredfholgate** [comment]
@johnlokerse Moved to #27

**Pull request merged**
